### ISSUE TITLE
[bug] - Example update key duplication

### ISSUE THREAD

**Issue by Olyno** [genderev/assassin#1]
Hi 👋 

I discovered the project recently via [dev.to](https://dev.to), and it seems really cool!
I figured a little problem about the demo: the update part seems to duplicate the key

![https://i.imgur.com/okVAtSX.png](https://i.imgur.com/okVAtSX.png)

I guess it's not a normal thing, so I report you this bug 😄 

Anyway, great job for your project!

**Comment by genderev** [comment]
Thanks so much for submitting an issue and showing what the bug looks like! I think I fixed the bug. On my own machine, I recreated this bug, and then I changed the code and it looks like the bug is no longer there.

The new [dist](https://raw.githubusercontent.com/genderev/assassin/master/dist/assassin.js) should solve this issue. Make a new issue if you see any bugs! Thanks so much for your feedback.
